# Generated by Django 4.2.7 on 2024-03-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=4)),
                ('Status_Engenharia', models.CharField(choices=[('ALOJ', 'Alojamento'), ('DET', 'Detalhamento')], max_length=4)),
                ('Status_Projeto', models.CharField(choices=[('AND', 'Andamento'), ('REV', 'Revisao'), ('CRES', 'Revisao_Crestani'), ('FIM', 'Finalizado')], max_length=4)),
                ('Responsavel', models.CharField(max_length=12)),
                ('Corrigido', models.CharField(max_length=12)),
                ('Data_Alojamento', models.DateField()),
                ('Data_Detalhamento', models.DateField()),
            ],
        ),
    ]
