# Generated by Django 4.2.7 on 2024-03-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_corrigido_alter_jobs_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Corrigido',
            field=models.CharField(choices=[('Augusto', 'Augusto'), ('Alessandro', 'Alessandro'), ('Guilherme', 'Guilherme'), ('Gustavo', 'Gustavo')], max_length=12),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='Responsavel',
            field=models.CharField(choices=[('Augusto', 'Augusto'), ('Alessandro', 'Alessandro'), ('Guilherme', 'Guilherme'), ('Gustavo', 'Gustavo')], max_length=12),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='Status_Engenharia',
            field=models.CharField(choices=[('Alojamento', 'Alojamento'), ('Detalhamento', 'Detalhamento')], max_length=12),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='Status_Projeto',
            field=models.CharField(choices=[('Andamento', 'Andamento'), ('Revisão', 'Revisao'), ('Crestani', 'Revisao_Crestani'), ('Finalizado', 'Finalizado')], max_length=10),
        ),
    ]
