# Generated by Django 4.2.7 on 2024-03-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobs_corrigido_alter_jobs_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Data_Alojamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='Data_Detalhamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
