# Generated by Django 5.0.1 on 2024-01-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Job', models.IntegerField()),
                ('qtdPontos', models.IntegerField()),
                ('qtdResistencia', models.IntegerField()),
                ('formatoBloco', models.CharField(max_length=2)),
                ('entreCentrosX', models.IntegerField()),
                ('entreCentrosY', models.IntegerField()),
                ('obs', models.CharField(max_length=200)),
            ],
        ),
    ]
