# Generated by Django 5.0.1 on 2024-01-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blocos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='pdf',
            field=models.FileField(default='media/pdfs/ola.pdf', upload_to='media/pdfs'),
        ),
    ]
