# Generated by Django 5.0.1 on 2024-01-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blocos', '0003_formato_alter_produto_formatobloco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Serie', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='Serie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='serieBlocos', to='Blocos.serie'),
            preserve_default=False,
        ),
    ]
