# Generated by Django 5.0.1 on 2024-02-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blocos', '0004_serie_produto_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='Job',
            field=models.CharField(max_length=4),
        ),
    ]
