# Generated by Django 5.0.1 on 2024-02-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blocos', '0006_alter_produto_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='Job',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='produto',
            name='obs',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
