# Generated by Django 5.0.1 on 2024-02-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blocos', '0007_alter_produto_job_alter_produto_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='obs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
