# Generated by Django 4.2.7 on 2024-03-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blocos', '0009_alter_produto_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pdf',
            field=models.FileField(default='ola.pdf', upload_to=''),
        ),
    ]
